production:
  url: 'http://127.0.0.1:8001/api/v1/audits'
staging:
  url: 'http://localhost:8001/api/v1/audits'
development:
  url: 'http://localhost:8001/api/v1/audits'
test:
  url: 'http://127.0.0.1:80011/api/v1/audits'
