production:
  url: 'http://lifebook.lifebliss-singapore.org/api/v1/participant'
staging:
  url: 'http://localhost/api/v1/participant'
development:
  url: 'http://localhost:3001/api/v1/participant'
test:
  url: 'http://localhost:30011/api/v1/participant'
